# Generated by Django 5.2 on 2025-05-25 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_event_max_participants_membership_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
