# Generated by Django 5.2.1 on 2025-05-25 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_club_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('disbanded', 'Disbanded')], default='pending', max_length=20),
        ),
    ]
