# Generated by Django 5.2 on 2025-05-25 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_club_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='foundation_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
