# Generated by Django 5.2 on 2025-05-25 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_club_foundation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='max_member',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
