# Generated by Django 5.2.1 on 2025-05-25 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_club_max_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='position',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
