# Generated by Django 5.2.1 on 2025-05-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_membership_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='max_member',
            field=models.PositiveIntegerField(),
        ),
    ]
