# Generated by Django 5.2.1 on 2025-05-25 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event_end_date_event_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
