# Generated by Django 5.2.1 on 2025-05-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_rename_max_participants_event_quota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='payment_methods',
            field=models.JSONField(default=dict),
        ),
    ]
