# Generated by Django 5.2.1 on 2025-05-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_event_payment_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventparticipation',
            name='payment_method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
