# Generated by Django 5.2.1 on 2025-05-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_event_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='status',
            field=models.CharField(choices=[('active', '營運中'), ('pending', '待審核'), ('rejected', '已拒絕'), ('suspended', '暫停營運'), ('disbanded', '已解散')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planning', '尚未接受報名'), ('open', '接受報名中'), ('closed', '已截止報名'), ('completed', '已結束'), ('cancelled', '已取消')], default='planning', max_length=20),
        ),
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.CharField(choices=[('pending', '待審核'), ('accepted', '已加入'), ('rejected', '已拒絕'), ('left', '已退出')], default='pending', max_length=10),
        ),
    ]
