# Generated by Django 5.2.1 on 2025-05-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_contact_user_name_alter_club_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='club_images/'),
        ),
    ]
