# Generated by Django 5.2.1 on 2025-05-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_club_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開活動'),
        ),
    ]
